package io.github.nemanjan00.pm3.termux

import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import io.github.nemanjan00.pm3.bridge.TcpBridge

/**
 * Wires the bridge into a stock Termux install.
 *
 * This app is not a Termux plugin in the strict sense. A real plugin declares
 * `android:sharedUserId="com.termux"` (see termux-api's manifest) and must
 * therefore be signed with the *same key* as the installed Termux -- so a
 * third-party plugin cannot be installed next to the F-Droid build at all.
 *
 * Instead we use the public RUN_COMMAND service, which any app may call given
 * the com.termux.permission.RUN_COMMAND permission and the user's consent. We
 * drop a small `pm3` wrapper into Termux's bin directory; from then on `pm3` in
 * any Termux session connects through this app's bridge.
 *
 * Constants mirror termux-shared's TermuxConstants rather than being imported,
 * because depending on termux-shared would pull the whole Termux build in.
 */
class TermuxIntegration(private val context: Context) {

    val isTermuxInstalled: Boolean
        get() = try {
            context.packageManager.getPackageInfo(TERMUX_PACKAGE, 0)
            true
        } catch (_: PackageManager.NameNotFoundException) {
            false
        }

    val hasRunCommandPermission: Boolean
        get() = context.checkSelfPermission(PERMISSION_RUN_COMMAND) ==
            PackageManager.PERMISSION_GRANTED

    /**
     * Installs the `pm3` wrapper into Termux's $PREFIX/bin.
     *
     * Written by asking Termux to run the heredoc itself: this app cannot write
     * into Termux's private data directory directly -- that is exactly the
     * isolation sharedUserId would have removed.
     */
    fun installWrapper(port: Int = TcpBridge.DEFAULT_PORT) {
        val script = wrapperScript(port)
        // Base64 avoids every quoting hazard in handing a multi-line script
        // through an intent extra and into a shell.
        val encoded = android.util.Base64.encodeToString(
            script.toByteArray(), android.util.Base64.NO_WRAP,
        )
        runCommand(
            executable = "$TERMUX_BIN/sh",
            arguments = arrayOf(
                "-c",
                "echo $encoded | base64 -d > $TERMUX_BIN/pm3 && chmod +x $TERMUX_BIN/pm3 && " +
                    "echo 'pm3 wrapper installed; run: pm3'",
            ),
            background = false,
        )
    }

    /** Opens an interactive client in a Termux session through the bridge. */
    fun openSession(port: Int = TcpBridge.DEFAULT_PORT) {
        runCommand(
            executable = "$TERMUX_BIN/pm3",
            arguments = emptyArray(),
            background = false,
        )
    }

    private fun runCommand(executable: String, arguments: Array<String>, background: Boolean) {
        val intent = Intent().apply {
            setClassName(TERMUX_PACKAGE, RUN_COMMAND_SERVICE)
            action = ACTION_RUN_COMMAND
            putExtra(EXTRA_COMMAND_PATH, executable)
            putExtra(EXTRA_ARGUMENTS, arguments)
            putExtra(EXTRA_WORKDIR, TERMUX_HOME)
            putExtra(EXTRA_BACKGROUND, background)
            putExtra(EXTRA_SESSION_ACTION, SESSION_ACTION_OPEN_ACTIVITY)
            putExtra(EXTRA_COMMAND_LABEL, "Proxmark3 bridge")
        }
        context.startForegroundService(intent)
    }

    /**
     * The wrapper.
     *
     * It prefers the Termux-packaged client when one is installed (the user
     * chose that version, and `pkg upgrade` keeps it current) and otherwise
     * falls back to the one shipped in this APK. The APK copy lives in the
     * app's nativeLibraryDir, which is world-readable and executable, so Termux
     * can exec it directly -- no copying, and no second copy to keep in sync.
     */
    private fun wrapperScript(port: Int): String {
        val bundled = context.applicationInfo.nativeLibraryDir + "/libproxmark3.so"
        return """
            #!$TERMUX_BIN/sh
            # Generated by pm3-droid. Connects to the app's transport bridge.
            #
            # The app owns the USB/Bluetooth link and exposes it on loopback;
            # the client speaks tcp: natively, so nothing here needs a driver.
            PORT=${'$'}{PM3_PORT:-$port}
            ADDR="tcp:127.0.0.1:${'$'}PORT"

            if command -v proxmark3 >/dev/null 2>&1; then
                CLIENT=proxmark3          # pkg install proxmark3
            elif [ -x "$bundled" ]; then
                CLIENT="$bundled"         # bundled in the pm3-droid APK
            else
                echo "No proxmark3 client found." >&2
                echo "Install one with: pkg install proxmark3" >&2
                exit 1
            fi

            if ! exec 3<>/dev/tcp/127.0.0.1/${'$'}PORT 2>/dev/null; then
                echo "Nothing is listening on 127.0.0.1:${'$'}PORT." >&2
                echo "Open pm3-droid and connect a device to start the bridge." >&2
                exit 1
            fi
            exec 3<&- 3>&-

            exec "${'$'}CLIENT" "${'$'}ADDR" "${'$'}@"
        """.trimIndent()
    }

    companion object {
        const val TERMUX_PACKAGE = "com.termux"
        const val PERMISSION_RUN_COMMAND = "com.termux.permission.RUN_COMMAND"

        private const val RUN_COMMAND_SERVICE = "com.termux.app.RunCommandService"
        private const val ACTION_RUN_COMMAND = "com.termux.RUN_COMMAND"
        private const val EXTRA_COMMAND_PATH = "com.termux.RUN_COMMAND_PATH"
        private const val EXTRA_ARGUMENTS = "com.termux.RUN_COMMAND_ARGUMENTS"
        private const val EXTRA_WORKDIR = "com.termux.RUN_COMMAND_WORKDIR"
        private const val EXTRA_BACKGROUND = "com.termux.RUN_COMMAND_BACKGROUND"
        private const val EXTRA_SESSION_ACTION = "com.termux.RUN_COMMAND_SESSION_ACTION"
        private const val EXTRA_COMMAND_LABEL = "com.termux.RUN_COMMAND_COMMAND_LABEL"

        /** Open the session's activity and make it the current session. */
        private const val SESSION_ACTION_OPEN_ACTIVITY = "0"

        private const val TERMUX_FILES = "/data/data/com.termux/files"
        private const val TERMUX_BIN = "$TERMUX_FILES/usr/bin"
        private const val TERMUX_HOME = "$TERMUX_FILES/home"
    }
}
